name: assistant-logement
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - faiss-cpu
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pip:
      - streamlit
      - sentence-transformers
      - transformers
      - accelerate
      - faiss-cpu
      - bitsandbytes
